// sprites.js — Pixel-Art als Textmatrizen. Keine Binärassets, alles versionierbar.
// Ein Körper pro Haltung; Kleidung und Farben kommen aus den Palettenvarianten.

// Der Geiger selbst: 16x24, damit er auf dem Handy lesbar bleibt.
// Ein Körper, drei Klüfte — die Kleiderordnung entsteht über die Palette.
export const ROLAND_FRAMES = {
  idle: [
    '  hhhHHHhhhhhh  ',
    '  hhhhhhhhhhhh  ',
    '  hhhhhhhhhhhh  ',
    '  hhsssssssshh  ',
    '  hhsssssssshh  ',
    '  hhs.ssss.shh  ',
    '  hhsssssssshh  ',
    '  hhSssssssShh  ',
    '  hhssSSSSsshh  ',
    '      SSSS      ',
    '  aawwwwwwwwaa  ',
    ' aaaawwrrwwaaaa ',
    ' aaaawwrrwwaaaa ',
    ' aaaawwrrwwaaaa ',
    ' aaaawwrrwwaaaa ',
    ' aaaawwrrwwaaaa ',
    ' aaaawwrrwwaaaa ',
    '  aaaaaaaaaaaa  ',
    '  aaaaaaaaaaaa  ',
    '  aaaa    aaaa  ',
    '  aaaa    aaaa  ',
    '  aaaa    aaaa  ',
    '  aaaa    aaaa  ',
    ' bbbbb    bbbbb ',
  ],
  walk1: [
    '  hhhHHHhhhhhh  ',
    '  hhhhhhhhhhhh  ',
    '  hhhhhhhhhhhh  ',
    '  hhsssssssshh  ',
    '  hhsssssssshh  ',
    '  hhs.ssss.shh  ',
    '  hhsssssssshh  ',
    '  hhSssssssShh  ',
    '  hhssSSSSsshh  ',
    '      SSSS      ',
    '  aawwwwwwwwaa  ',
    ' aaaawwrrwwaaa  ',
    ' aaaawwrrwwaaa  ',
    ' aaaawwrrwwaaaa ',
    ' aaaawwrrwwaaaa ',
    ' aaaawwrrwwaaaa ',
    ' aaaawwrrwwaaaa ',
    '  aaaaaaaaaaaaa ',
    '  aaaaaaaaaaaaa ',
    '   aaaa  aaaa   ',
    '   aaaa  aaaa   ',
    '   aaaa  aaaa   ',
    '   aaaa  aaaa   ',
    ' bbbbbb  bbbbbb ',
  ],
  walk2: [
    '  hhhHHHhhhhhh  ',
    '  hhhhhhhhhhhh  ',
    '  hhhhhhhhhhhh  ',
    '  hhsssssssshh  ',
    '  hhsssssssshh  ',
    '  hhs.ssss.shh  ',
    '  hhsssssssshh  ',
    '  hhSssssssShh  ',
    '  hhssSSSSsshh  ',
    '      SSSS      ',
    '  aawwwwwwwwaa  ',
    '  aaawwrrwwaaaa ',
    '  aaawwrrwwaaaa ',
    ' aaaawwrrwwaaaa ',
    ' aaaawwrrwwaaaa ',
    ' aaaawwrrwwaaaa ',
    ' aaaawwrrwwaaaa ',
    ' aaaaaaaaaaaaa  ',
    ' aaaaaaaaaaaaa  ',
    '  aaaa    aaaa  ',
    '  aaaa    aaaa  ',
    '  aaaa    aaaa  ',
    '  aaaa    aaaa  ',
    'bbbbbb    bbbbbb',
  ],
  jump: [
    '  hhhHHHhhhhhh  ',
    '  hhhhhhhhhhhh  ',
    '  hhhhhhhhhhhh  ',
    '  hhsssssssshh  ',
    '  hhsssssssshh  ',
    '  hhs.ssss.shh  ',
    '  hhsssssssshh  ',
    '  hhSssssssShh  ',
    '  hhssSSSSsshh  ',
    '      SSSS      ',
    ' aaawwwwwwwwaaa ',
    ' aaaawwrrwwaaaa ',
    ' aaaawwrrwwaaaa ',
    ' aaaawwrrwwaaaa ',
    ' aaaawwrrwwaaaa ',
    ' aaaawwrrwwaaaa ',
    '  aaawwrrwwaaa  ',
    '  aaaaaaaaaaaa  ',
    '  aaaaaaaaaaaa  ',
    '   aaaa  aaaa   ',
    '   aaaa  aaaa   ',
    '   aaaa  aaaa   ',
    '   aaaa  aaaa   ',
    ' bbbbbb  bbbbbb ',
  ],
  duck: [
    '  hhhHHHhhhhhh  ',
    '  hhhhhhhhhhhh  ',
    '  hhhhhhhhhhhh  ',
    '  hhsssssssshh  ',
    '  hhsssssssshh  ',
    '  hhs.ssss.shh  ',
    '  hhsssssssshh  ',
    '  hhSssssssShh  ',
    '  hhssSSSSsshh  ',
    '  aawwwwwwwwaa  ',
    ' aaaawwrrwwaaaa ',
    ' aaaawwrrwwaaaa ',
    ' aaaawwrrwwaaaa ',
    ' aaaaaaaaaaaaaa ',
    ' aaaaaaaaaaaaaa ',
    ' aaaaa    aaaaa ',
    '  aaaa    aaaa  ',
    '  aaaa    aaaa  ',
    '  aaaa    aaaa  ',
    ' bbbbb    bbbbb ',
  ],
};

// Interludium: Motorrad von hinten (Fahrer mit Helm)
const MOTORRAD = [
  '     hhhhhh     ',
  '    hhhhhhhh    ',
  '    h......h    ',
  '    h.cccc.h    ',
  '   kkkkkkkkkk   ',
  '   kkkkkkkkkk   ',
  ' kkkkkkkkkkkkkk ',
  ' kkrrrrrrrrrrkk ',
  ' kkrrrrrrrrrrkk ',
  ' kkkkkkkkkkkkkk ',
  ' bb kkkkkkkk bb ',
  ' bb kkkkkkkk bb ',
  '   kkkkkkkkkk   ',
  '   kkkkkkkkkk   ',
  '  mmyyyyyyyymm  ',
  '  mm  rOOr  mm  ',
  '  mm dddddd mm  ',
  '  mm dddddd mm  ',
  '  mm dddddd mm  ',
  '  mm dddddd mm  ',
  '     dddddd     ',
  '    dddddddd    ',
];

// Nasses Laub auf der Fahrbahn
const LAUB = [
  '     oOo     ',
  '   oOooOo  o ',
  '  ooOooOooOo ',
  '    oooOoo   ',
  '      oo     ',
  '             ',
];

// Epilog: Ramona am Grill
const RAMONA = [
  '    rrrrrr    ',
  '   rrrrrrrr   ',
  '   rrrrrrrr   ',
  '   rssssssr   ',
  '    s.ss.s    ',
  '    ssssss    ',
  '    ssssss    ',
  '     SSSS     ',
  '   pppppppp   ',
  '  spppppppps  ',
  '  saaaaaaaas  ',
  '  saaaaaaaas  ',
  '  saaaaaaaam  ',
  '  saaaaaaaam  ',
  '    pppppp m  ',
  '    pppppp mm ',
  '    pppppp    ',
  '    pp  pp    ',
  '    pp  pp    ',
  '    pp  pp    ',
  '    pp  pp    ',
  '   ddd  ddd   ',
];

// Epilog: der Grill (Glut, Wuerste)
const GRILL = [
  '                    ',
  '                    ',
  '                    ',
  '                    ',
  '  mmmbbmbbbmmbbmmm  ',
  '  mkkoookooookooom  ',
  '  mkkkkkkkkkkkkkkm  ',
  '  mmmmmmmmmmmmmmmm  ',
  '    m          m    ',
  '    m  mmmmmm  m    ',
  '    m          m    ',
  '    m          m    ',
];

// Akt 4: Nervennahrung
const BREZEL = [
  '  ..aa..  ',
  ' .aawwaa. ',
  ' aawwwwwa ',
  ' aa.ww.aa ',
  ' .aawwaa. ',
  '..aawwaa..',
  "........'",
];
export const SPRITES = {
  ramona: RAMONA,
  grill: GRILL,
  laub: LAUB,
  brezel: BREZEL,
  motorrad: MOTORRAD,
  roland_idle: ROLAND_FRAMES.idle,
  roland_walk1: ROLAND_FRAMES.walk1,
  roland_walk2: ROLAND_FRAMES.walk2,
  roland_jump: ROLAND_FRAMES.jump,
  roland_duck: ROLAND_FRAMES.duck,

  // Piccolo: der erste Gegner — als Flötist mit silberner Flöte erkennbar
  piccolo: [
    '     dddd     ',
    '     dddd     ',
    '    dddddd    ',
    '    s.ss.s    ',
    '    ssssss    ',
    '    ssssymmmym',
    '    skkkks    ',
    '     kkkk     ',
    '   KKKKKKKK   ',
    '  kkkkwwkkkk  ',
    '  kkkkwwkkkk  ',
    '  kkkkwwkkkk  ',
    '  kkkkwwkkkk  ',
    '    kkkkkk    ',
    '    kkkkkk    ',
    '    kk  kk    ',
    '    kk  kk    ',
    '   ddd  ddd   ',
  ],

  // Sopran: hoch, offener Mund, gefährlich laut
  sopran: [
    '.....dd.....',
    '....dddd....',
    '....ssss....',
    '....s..s....',
    '....ssss....',
    '....s..s....',
    '....SSSS....',
    '...pppppp...',
    '..pppppppp..',
    '..pppppppp..',
    '..pppppppp..',
    '..pppppppp..',
    '...pppppp...',
    '...pppppp...',
    '...pppppp...',
    '....pppp....',
    '....p..p....',
    '....p..p....',
    '...dd..dd...',
  ],

  // Tenor: breit, Notenmappe vor dem Bauch, verschleppt das Tempo
  tenor: [
    '.....gggg.....',
    '....gggggg....',
    '....gssssg....',
    '....ssssss....',
    '....ssssss....',
    '.....SSSS.....',
    '...kkkkkkkk...',
    '..kkkkkkkkkk..',
    '..kkkmmmmkkk..',
    '..kkkmmmmkkk..',
    '..kkkkkkkkkk..',
    '...kkkkkkkk...',
    '...kkkkkkkk...',
    '...kkk..kkk...',
    '...kkk..kkk...',
    '...dd....dd...',
  ],

  // Dirigent: Frack, Binder, erhobener Taktstock
  dirigent: [
    '    dddddd    ',
    '    ddddddy   ',
    '    ddddddy   ',
    '    ssssssy   ',
    '    s.ss.sy   ',
    '    ssssssy   ',
    '    ssssssy   ',
    '     ssss y k ',
    '  kkkwwwwkykk ',
    '  kkkkrrkkkkk ',
    ' kkkkkrrkkkk  ',
    ' kkkkkrrkkkk  ',
    ' kkkkkrrkkkk  ',
    ' kkkkkwwkkkk  ',
    ' kkkkkkkkkkk  ',
    '   kkkkkkkk   ',
    '   kkkkkkkk   ',
    '   kkk  kkk   ',
    '   kkk  kkk   ',
    '   kkk  kkk   ',
    '   kkk  kkk   ',
    '  ....  ....  ',
  ],

  // Instrumentenkoffer: helles Leder mit Messing, damit er sich vom Fels abhebt
  koffer: [
    '      ....      ',
    ' .............. ',
    ' .MMMyMMMMyMMM. ',
    ' .LLLyLLLLyLLL. ',
    ' .LLLyLLLLyLLL. ',
    ' .LLLyLyyLyLLL. ',
    ' .LLLyLyyLyLLL. ',
    ' .LLLyLLLLyLLL. ',
    ' .LLLyLLLLyLLL. ',
    ' .LLLyLLLLyLLL. ',
    ' .............. ',
    '                ',
  ],

  bierdeckel: [
    '..yyyy..',
    '.ywwwwy.',
    'ywWWWWwy',
    'ywWWWWwy',
    'ywWWWWwy',
    'ywWWWWwy',
    '.ywwwwy.',
    '..yyyy..',
  ],

  ohropax: [
    '........',
    '.oo..oo.',
    'oooooooo',
    'oooooooo',
    '.oo..oo.',
    '........',
  ],

  wasser: [
    '...GG...',
    '..GGGG..',
    '..c..c..',
    '.cccccc.',
    '.cCCCCc.',
    '.cCCCCc.',
    '.cCCCCc.',
    '.cCCCCc.',
    '.cCCCCc.',
    '.cccccc.',
  ],

  bier: [
    '..wwwwww..',
    '.wWWWWWWw.',
    '.wWWWWWWw.',
    '.yyyyyyyy.',
    '.yYYYYYYy.',
    '.yYYYYYYy.',
    '.yYYYYYYy.',
    '.yYYYYYYy.',
    '.yYYYYYYy.',
    '..yYYYYy..',
    '..yYYYYy..',
    '..yyyyyy..',
    '...yyyy...',
  ],

  mappe: [
    '.kkkkkkkkkk.',
    '.kWWWWWWWWk.',
    '.kW..W..WWk.',
    '.kWWWWWWWWk.',
    '.kW..W..WWk.',
    '.kW..W..WWk.',
    '.kWWWWWWWWk.',
    '.kW..W..WWk.',
    '.kWWWWWWWWk.',
    '.kWWWWWWWWk.',
    '.kkkkkkkkkk.',
    '...kk..kk...',
  ],

  // ---- Interludium: Cabrio, Verkehr und Straßenrand ----
  mx5: [
    '                          ',
    '  ......................  ',
    '  .dddddd........dddddd.  ',
    '   d........dd........d   ',
    '  yyy.......dd.......yyy  ',
    ' ryyyrrrrrrrrrrrrrrrryyyr ',
    ' ryyyRRRRRRRRRRRRRRRRyyyr ',
    ' rrrrrrrrrrrrrrrrrrrrrrrr ',
    ' rrrrrrrrrrrrrrrrrrrrrrrr ',
    ' r..........rr..........r ',
    ' rrrrrrrrrrrrrrrrrrrrrrrr ',
    ' ammmmmmmmmmmmmmmmmmmmaaa ',
    ' aaaaaaaaaammmmaaaaaaaaaa ',
    '......              ......',
    '......              ......',
    '......              ......',
  ],

  auto: [
    '                    ',
    '  KKKKKKKKKKKKKKKK  ',
    '  KeeeeeeeeeeeeeeK  ',
    '  KeeeeeeeeeeeeeeK  ',
    '  KKKKKKKKKKKKKKKK  ',
    '  KKKKKKKKKKKKKKKK  ',
    '  KKKKKKKKKKKKKKKK  ',
    '  KKKKKKKKKKKKKKKK  ',
    '  KKKKKKKKKKKKKKKK  ',
    ' KKKKKKKKKKKKKKKKKK ',
    '....yyyKKKKKKyyy....',
    '....            ....',
    '....            ....',
  ],

  lkw: [
    '                              ',
    '            yyyyyy            ',
    '  ggggggggggyyyyyygggggggggg  ',
    '  gGGGGGGGGGGGGGGGGGGGGGGGGg  ',
    '  gGGGGGGGGGGGGGGGGGGGGGGGGg  ',
    '  gGGGGGGGGGGGGGGGGGGGGGGGGg  ',
    '  gggggggggggggggggggggggggg  ',
    '  ggGGGGGGGGGGGGGGGGGGGGGGgg  ',
    '  ggGKKKKKKKKKKKKKKKKKKKKGgg  ',
    '  ggGKKKKKKKKKKKKKKKKKKKKGgg  ',
    '  ggGKKKKKKKKKKKKKKKKKKKKGgg  ',
    '  ggGKKKKKKKKKKKKKKKKKKKKGgg  ',
    '  ggGKKKKKKKKKKKKKKKKKKKKGgg  ',
    '  ggGGGGGGGGGGGGGGGGGGGGGGgg  ',
    '  gggggggggggggggggggggggggg  ',
    '......gggggggggggggggggg......',
    '......KKKKKKKKKKKKKKKKKK......',
    '......yyKKKKKKKKKKKKKKyy......',
    '......                  ......',
    '......                  ......',
  ],

  baum: [
    '                ',
    '                ',
    '     EEEEEE     ',
    '     EEEEEE     ',
    '    EEEEEEEE    ',
    '    EEEEEEEE    ',
    '  eeEEEEEEEEee  ',
    '  eeEEEEEEEEee  ',
    '  eeEEEEEEeeee  ',
    '  eeEEEEEEeeee  ',
    '  eeEEEEEEeeee  ',
    '  eeEEEEEEeeee  ',
    '  eeEEEEEEeeee  ',
    '  eeEEEEEEeeee  ',
    '  eeEEEEEEEEee  ',
    '  eeEEEEEEEEee  ',
    '  eeEEEEEEEEee  ',
    '  eeEEEEEEEEee  ',
    '  eeeeeeeeeeee  ',
    '  eeeeeeeeeeee  ',
    '  eeeeeeeeeeee  ',
    '  eeeeeeeeeeee  ',
    '      eeee      ',
    '      eeee      ',
    '      eeee      ',
    '      eeee      ',
    '      eeee      ',
    '      eeee      ',
  ],

  schild: [
    '              ',
    ' oooooooooooo ',
    ' oOOOOOOOOOOo ',
    ' oOOOOOOOOOOo ',
    ' oOOO....OOOo ',
    ' oOOO....OOOo ',
    ' oOOOOOOOOOOo ',
    ' oooooooooooo ',
    '      mm      ',
    '      mm      ',
    '      mm      ',
    '      mm      ',
    '      mm      ',
    '      mm      ',
    '      mm      ',
    '      mm      ',
    '      mm      ',
    '      mm      ',
    '      mm      ',
    '      mm      ',
  ],

  blitzer: [
    '   yyyyyyyyyy   ',
    '   yyyyyyyyyy   ',
    '   yyyyyyyyyy   ',
    '   yyyyyyyyyy   ',
    '  mmmmmmmmmmmm  ',
    '  mmmmmmmmmmmm  ',
    '  mmyyyyyyyymm  ',
    '  mmyOOOOOOymm  ',
    '  mmyOO..OOymm  ',
    '  mmyyyyyyyymm  ',
    '  mmmmmmmmmmmm  ',
    '  mmmmmmmmmmmm  ',
    '       gg       ',
    '       gg       ',
    '       gg       ',
    '       gg       ',
    '       gg       ',
    '       gg       ',
    '       gg       ',
    '       gg       ',
    '       gg       ',
    '       gg       ',
    '    KKKKKKKK    ',
    '    KKKKKKKK    ',
  ],

  notenstaender: [
    ' kkkkkkkkkk ',
    ' kwwwwwwwwk ',
    ' kw......wk ',
    ' kww....wwk ',
    ' kwwwwwwwwk ',
    ' kwwwwwwwwk ',
    ' kkkkkkkkkk ',
    '     mm     ',
    '     mm     ',
    '     mm     ',
    '     mm     ',
    '     mm     ',
    '     mm     ',
    '     mm     ',
    '  mmmmmmmm  ',
    '  mmmmmmmm  ',
  ],

  // Schlagloch auf der Fahrbahn
  schlagloch: [
    '                ',
    '                ',
    '  mmmmmmmmmmmm  ',
    ' mm..........mm ',
    ' mm.KKKKKKKK.mm ',
    ' mm.KKKKKKKK.mm ',
    ' mm..........mm ',
    '  mmmmmmmmmmmm  ',
    '                ',
  ],

  // Notenblatt, vom Wind getragen
  blatt: [
    ' .......... ',
    ' .wwwwwwww. ',
    ' .wKKKKw.w. ',
    ' .wwwwwwww. ',
    ' .wKKKKwww. ',
    ' .wwwwwwww. ',
    ' .wKKKKKww. ',
    ' .wwwwwwww. ',
    ' .wwwwwwww. ',
    ' .......... ',
  ],

  tuer: [
    'aaaaaaaaaaaaaaaa',
    'ammmmmmmmmmmmmmo',
    'amo..........omo',
    'amo..........omo',
    'amo..........omo',
    'amo..........omo',
    'amo.....yy...omo',
    'amo..........omo',
    'amo..........omo',
    'amo..........omo',
    'amo..........omo',
    'amo..........omo',
    'amo..........omo',
    'amo..........omo',
    'amo..........omo',
    'aaaaaaaaaaaaaaaa',
  ],

  // Kleiderschrank der Laube: die Endstation für den Frack.
  schrank: [
    'LLLLLLLLLLLLLLLL',
    'LddddddddddddddL',
    'LddddddLLddddddL',
    'LddddddLLddddddL',
    'LddddddLLddddddL',
    'LddddddLLddddddL',
    'LddddddLLddddddL',
    'LddddddLLddddddL',
    'LddddddLLddddddL',
    'LddddddLLddddddL',
    'LddddddLLddddddL',
    'LddddddLLddddddL',
    'LddddddLLddddddL',
    'LdddddyLLydddddL',
    'LdddddyLLydddddL',
    'LddddddLLddddddL',
    'LddddddLLddddddL',
    'LddddddLLddddddL',
    'LddddddLLddddddL',
    'LddddddLLddddddL',
    'LddddddLLddddddL',
    'LddddddLLddddddL',
    'LddddddLLddddddL',
    'LddddddLLddddddL',
    'LddddddLLddddddL',
    'LddddddLLddddddL',
    'LddddddddddddddL',
    'LL            LL',
  ],

  // Anna ist die Konzertmeisterin. Türkise Strickjacke, dunkler Bob und
  // die goldene Stimmgabel unterscheiden sie auch bei 1x-Pixelauflösung.
  // Der Sprite-Schlüssel 'ada' bleibt aus Kompatibilitätsgründen stabil.
  ada: [
    '    dddddd    ',
    '   dddddddd   ',
    '   ddssssdd   ',
    '   ds.sssd    ',
    '   dsssssd    ',
    '    sSSss     ',
    '     ssss  y  ',
    '  cccwwwwcccy ',
    ' cccccwwccccy ',
    ' cccccwwccc y ',
    ' ccccccccc  y ',
    ' ccccccccc    ',
    '  cccccccc    ',
    '  cccccccc    ',
    '   KKKKKK     ',
    '   KKKKKK     ',
    '   KKKKKK     ',
    '   KKKKKK     ',
    '   KK  KK     ',
    '   KK  KK     ',
    '   ..  ..     ',
    '   ..  ..     ',
  ],

  // Drei Instrumentengruppen, drei Silhouetten: nicht nur drei Kopien desselben
  // Sammelobjekts. Randfarbe und Notenbild bleiben auch im Vorbeilaufen lesbar.
  stimme_violine: [
    ' yyyyyyyy ', 'yyyyyyyyy ', 'ywwwwwwwy ', 'yw..K..wy ',
    'ywwwKKwwy ', 'yw...K.wwy', 'ywwwwKwwwy', 'yw...K.www',
    'ywwwwKwwwy', 'yw...K.www', 'ywwwwwwwwy', ' yyyyyyyyy',
  ],
  stimme_bratsche: [
    'cccccccccc', 'cwwwwwwwwc', ' cwKK..wwc', 'cwwK.Kwwwc',
    'cwwKK..wwc', ' cwK.Kwwwc', 'cwwwKK.www', ' cwwK.Kwwc',
    'cwwwKK.www', 'cwwwwwwwwc', ' cwwwwwwwc', 'cccccccccc',
  ],
  stimme_bass: [
    '  oooooo  ', ' oooooooo ', 'oooooooooo', 'owKKwwKKwo',
    'owKKwwKKwo', 'owwwKKwwwo', 'owwwKKwwwo', 'owKKwwKKwo',
    'owKKwwKKwo', 'oooooooooo', ' oooooooo ', '  oooooo  ',
  ],

  // Raumsilhouetten für Akt 1. Sie sind reine Kulisse und können als `decor`
  // in jeder Leveldefinition platziert werden.
  spinde: [
    'gggggggggggggggggggggggggggggggg',
    'gGGGGGGGGGGGGGggGGGGGGGGGGGGGGg',
    'gG....G....G..GggG....G....G..Gg',
    'gG....G....G..GggG....G....G..Gg',
    'gGggggGggggGggGggGggggGggggGggGg',
    'gG............GggG............Gg',
    'gG............GggG............Gg',
    'gG............GggG............Gg',
    'gG.....yy.....GggG.....yy.....Gg',
    'gG.....yy.....GggG.....yy.....Gg',
    'gG............GggG............Gg',
    'gG............GggG............Gg',
    'gG............GggG............Gg',
    'gGggggggggggggGggGggggggggggggGg',
    'gggggggggggggggggggggggggggggggg',
    'gg  gg                    gg  gg',
  ],
  geigenkasten: [
    '      ....      ', '   ...LLLL...   ', ' ..LLLLLLLLLL.. ',
    '.LMMMMMMMMMMMML.', '.LMMMyMMMMMyMML.', '.LMMMMMMMMMMMML.',
    '.LLLLLLLLLLLLLL.', ' ..LL......LL.. ',
  ],
  dienstplan41: [
    'yyyyyyyyyyyyyyyy', 'ywwwwwwwwwwwwwwy', 'ywKKKKKKKKKKKKwy',
    'ywKwwKwwKwwKKwy', 'ywKKwKwwKKwKKwy', 'ywKwwKwwKwwKKwy',
    'ywKKKKKKKKKKKKwy', 'yw....yyyy..wwy', 'ywwwwwwwwwwwwwwy',
    'yyyyyyyyyyyyyyyy',
  ],
  rohrwand: [
    'gggg      gggg      gggg      gggg',
    'gGGg      gGGg      gGGg      gGGg',
    'gGGg      gGGg      gGGg      gGGg',
    'gGGg      gGGg      gGGg      gGGg',
    'gGGg      gGGg      gGGg      gGGg',
    'gGGg      gGGg      gGGg      gGGg',
    'gGGg      gGGg      gGGg      gGGg',
    'gGGg      gGGg      gGGg      gGGg',
    'gGGg      gGGg      gGGg      gGGg',
    'gGGg      gGGg      gGGg      gGGg',
    'gGGg      gGGg      gGGg      gGGg',
    'gGGg      gGGg      gGGg      gGGg',
    'gGGg      gGGg      gGGg      gGGg',
    'gGGg      gGGg      gGGg      gGGg',
    'gGGg      gGGg      gGGg      gGGg',
    'gGGg      gGGg      gGGg      gGGg',
    'gGGg      gGGg      gGGg      gGGg',
    'gGGg      gGGg      gGGg      gGGg',
    'gGGgggggggGGggggggggGGggggggggGGg',
    'gGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGg',
    'gggggggggggggggggggggggggggggggg',
  ],
  gegengewicht: [
    '          gg          ',
    '          GG          ',
    '          gg          ',
    '          GG          ',
    '          gg          ',
    '          GG          ',
    '       gggggggg       ',
    '      gGGGGGGGGg      ',
    '     gGGGGGGGGGGg     ',
    '    gGGGyyyyyyGGGGg    ',
    '    gGGGy....yGGGGg    ',
    '    gGGGy.GG.yGGGGg    ',
    '    gGGGy.GG.yGGGGg    ',
    '    gGGGy....yGGGGg    ',
    '    gGGGyyyyyyGGGGg    ',
    '    gGGGGGGGGGGGGGg    ',
    '    gGGGGGGGGGGGGGg    ',
    '    gGGGGGGGGGGGGGg    ',
    '    gGGGGGGGGGGGGGg    ',
    '    gGGGGGGGGGGGGGg    ',
    '    gGGGGGGGGGGGGGg    ',
    '    gGGGGGGGGGGGGGg    ',
    '     ggggggggggggg     ',
    '       gg    gg        ',
    '       gg    gg        ',
    '      ....  ....       ',
    'gggggggggggggggggggggggg',
  ],
  rohrventil: [
    'gggg      gggg', 'gGGg      gGGg', ' gGGggggggGGg ',
    '  gGgyyyyGGg  ', 'gggGy....yGggg', 'gGGGy.yy.yGGGg',
    'gGGGy.yy.yGGGg', 'gggGy....yGggg', '  gGgyyyyGGg  ',
    ' gGGggggggGGg ', 'gGGg      gGGg', 'gggg      gggg',
  ],
  notenstapel: [
    '  wwwwwwwwww  ', '  wK..K...Kw  ', 'wwwwwwwwwwwwww',
    'w..KK...K...ww', 'wwwwwwwwwwwwww', '  wK...KK..Kw  ',
    '  wwwwwwwwww  ',
  ],
  notenregal: [
    'LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL',
    'LwwwwwwLwwwwwwLwwwwwwLwwwwwwL',
    'LwKKKwwLwwKKKwLwKwwKwLwwKKKwL',
    'LwwwwwwLwwwwwwLwwwwwwLwwwwwwL',
    'LMMMMMMLMMMMMMLMMMMMMLMMMMMML',
    'LwwKKwwLwKwwKwLwwKKwwLwKwwKwL',
    'LwwwwwwLwwwwwwLwwwwwwLwwwwwwL',
    'LMMMMMMLMMMMMMLMMMMMMLMMMMMML',
    'LwKwwKwLwwKKwwLwKwwKwLwwKKwwL',
    'LwwwwwwLwwwwwwLwwwwwwLwwwwwwL',
    'LMMMMMMLMMMMMMLMMMMMMLMMMMMML',
    'LL    LL    LL    LL    LL  LL',
  ],
  archivwagen: [
    '    LLLLLLLLLLLLLLLL    ', '    LwwwwwwwwwwwwwwL    ',
    '    LwKKwwKKwwKKwwwL    ', '    LLLLLLLLLLLLLLLL    ',
    '       LL      LL       ', ' LLLLLLLLLLLLLLLLLLLLLL ',
    ' LMMLMMLMMLMMLMMLMMLML ', ' LLLLLLLLLLLLLLLLLLLLLL ',
    '   ...          ...     ', '  .....        .....    ',
  ],
  lastenhaken: [
    '       gg       ', '      gGGg      ', '      gGGg      ',
    '      gGGg      ', '      gGGg      ', '      gGGg      ',
    '      gGGg      ', '      gGGg      ', '      gGGg      ',
    '      gGGg      ', '      gGGg      ', '     gGGGg      ',
    '    gGGGGg      ', '   gGGgGGg      ', '  gGGg gGGg     ',
    ' gGGg   gGGg    ', ' gGGg   gGGg    ', '  gGGgggGGg     ',
    '   gGGGGGg      ', '    ggggg       ',
  ],
  seilrolle: [
    '   gggggggggg   ', '  gGGGGGGGGGGg  ', ' gGGggggggGGGGg ',
    'gGGg......gGGGg', 'gGGg.gggg.gGGGg', 'gGGg.gGGg.gGGGg',
    'gGGg.gggg.gGGGg', 'gGGg......gGGGg', ' gGGggggggGGGGg ',
    '  gGGGGGGGGGGg  ', '   gggggggggg   ', '       gg       ',
    '       gg       ', '       gg       ', '       gg       ',
  ],

  // Raumrequisiten für Akt 2 (Die Probe). Reine Kulisse als `decor`,
  // ohne neue Physik. Stuhlreihe und Bühnenvorhang sind raumgroß
  // (>= 20 Zeilen, >= 24 Spalten), damit Saal und Bühne je ein
  // dominantes Motiv haben wie in Akt 1.
  probentafel: [
    'yyyyyyyyyyyyyyyy',
    'ywwwwwwwwwwwwwwy',
    'ywKKKKKKKKKKKKwy',
    'ywKwwKwwKKwKKwy',
    'ywKKwKwwKwKwKwy',
    'ywKwwKwwKKwKKwy',
    'ywKKKKKKKKKKKKwy',
    'ywwwwwwwwwwwwwwy',
    'yyyyyyyyyyyyyyyy',
    '  LL        LL  ',
  ],
  stuhlreihe: [
    'gggggggggggggggggggggggggggggggg',
    'gGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGg',
    'gG....G....G....G....G....G....Gg',
    'gG....G....G....G....G....G....Gg',
    'gGggggGggggGggggGggggGggggGggggGg',
    'gGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGg',
    'gG....G....G....G....G....G....Gg',
    'gG....G....G....G....G....G....Gg',
    'gGggggGggggGggggGggggGggggGggggGg',
    'gggggggggggggggggggggggggggggggg',
    'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
    'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
    '  LL      LL      LL      LL    ',
    '  LL      LL      LL      LL    ',
    ' MMMMMM  MMMMMM  MMMMMM  MMMMMM ',
    ' MMMMMM  MMMMMM  MMMMMM  MMMMMM ',
    '  LL      LL      LL      LL    ',
    '  LL      LL      LL      LL    ',
    '  LL      LL      LL      LL    ',
    '  LL      LL      LL      LL    ',
    '..      ..      ..      ..      ',
  ],
  notenpult: [
    '  wwwwwwwwww  ',
    '  wKwKwKwKww  ',
    '  wwwwwwwwww  ',
    '      KK      ',
    '      KK      ',
    '      KK      ',
    '    KKKKKK    ',
    '   KK    KK   ',
  ],
  scheinwerfer: [
    '    gggggggg    ',
    '   gGGGGGGGGg   ',
    '  gGGwwwwwwGGg  ',
    '  gGwYYYYYYwGGg ',
    '  gGwYwwwwYwGGg ',
    '  gGGwwwwwwGGg  ',
    '   gGGGGGGGGg   ',
    '    gggggggg    ',
    '       GG       ',
    '       GG       ',
    '     GGGGGG     ',
    '   gg      gg   ',
  ],
  buehnenvorhang: [
    'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
    'RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR',
    'RrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRr',
    'RrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRr',
    'RRrRRrRRrRRrRRrRRrRRrRRrRRrRRrRR',
    'RrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRr',
    'RrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRr',
    'RRrRRrRRrRRrRRrRRrRRrRRrRRrRRrRR',
    'RrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRr',
    'RrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRr',
    'RRrRRrRRrRRrRRrRRrRRrRRrRRrRRrRR',
    'RrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRr',
    'RrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRr',
    'RRrRRrRRrRRrRRrRRrRRrRRrRRrRRrRR',
    'RrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRr',
    'RrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRr',
    'RRrRRrRRrRRrRRrRRrRRrRRrRRrRRrRR',
    'RrRrRrRrRrRrRrRrRrRrRrRrRrRrRrRr',
    'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
    'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
    '..      ..      ..      ..      ',
  ],

  // Stimmblätter der Notenmappe (DRR-04): ein Blatt allein ist kein Auftritt.
  stimmblatt: [
    'LLLLLLLLLL',
    'LhhhhhhhhL',
    'Lh......hL',
    'LhhhhhhhhL',
    'Lh......hL',
    'LhhhhhhhhL',
    'Lh......hL',
    'LhhhhhhhhL',
    'Lh......hL',
    'LhhhhhhhhL',
    'Lh......hL',
    'LLLLLLLLLL',
  ],

  // Bank der Laube im Kleingarten: Holzlatten, zwei Beine, 32x10.
  bank: [
    '  MMMMMMMMMMMMMMMMMMMMMMMMMMMM  ',
    '  MMMMMMMMMMMMMMMMMMMMMMMMMMMM  ',
    '  LLLLLLLLLLLLLLLLLLLLLLLLLLLL  ',
    '  MMMMMMMMMMMMMMMMMMMMMMMMMMMM  ',
    '  LLLLLLLLLLLLLLLLLLLLLLLLLLLL  ',
    '   LL                      LL   ',
    '   LL                      LL   ',
    '   LL                      LL   ',
    '   LL                      LL   ',
    '   LL                      LL   ',
  ],
};

// Kleiderordnung als Palettenvarianten desselben Körpers.
export const OUTFIT_PALETTES = {
  schwarz: {
    '.': '#0b0810', h: '#c9c9d2', H: '#ffffff', s: '#e8b98a', S: '#c19063',
    a: '#20202a', w: '#20202a', r: '#20202a', b: '#14141c',
  },
  anzug: {
    '.': '#0b0810', h: '#c9c9d2', H: '#ffffff', s: '#e8b98a', S: '#c19063',
    a: '#2c2c3a', w: '#f0eee4', r: '#b0392f', b: '#141418',
  },
  frack: {
    '.': '#0b0810', h: '#cfcfd8', H: '#ffffff', s: '#e8b98a', S: '#c19063',
    a: '#191622', w: '#f0eee4', r: '#e8e6dc', b: '#0b0810',
  },
};

// Die Fahrzeug- und Szenensprites für die Interludien kommen in Phase P3.
